# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import custom_network_pb2 as custom__network__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in custom_network_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomNetworkServiceStub(object):
    """============================================================
    CustomNetworkService
    ============================================================
    gRPC 服务定义：单 RPC，双向流模式。

    调用流程（从客户端视角）：
    1. 客户端调用 DataChannel，建立长期存活的双向流
    2. 客户端先发送一条 handshake 消息（携带 client_id / client_name）
    3. UE 服务端验证并注册会话，此后进入数据交换阶段
    4. 客户端持续向流写入 frame 消息（上行：Python -> UE）
    5. UE 向流写入 frame 消息（下行：UE -> Python）
    6. 任一方关闭流或发生错误时，连接终止

    多客户端特性：
    - 不同 Python 进程各自建立独立的 DataChannel 流
    - 每个流的 handshake 使用不同的 client_id
    - UE 端内部维护 per-client 发送队列，回包按 client_id 精确路由
    - 客户端之间互不干扰、不广播
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DataChannel = channel.stream_stream(
                '/uhmp.customnetwork.CustomNetworkService/DataChannel',
                request_serializer=custom__network__pb2.StreamMessage.SerializeToString,
                response_deserializer=custom__network__pb2.StreamMessage.FromString,
                _registered_method=True)


class CustomNetworkServiceServicer(object):
    """============================================================
    CustomNetworkService
    ============================================================
    gRPC 服务定义：单 RPC，双向流模式。

    调用流程（从客户端视角）：
    1. 客户端调用 DataChannel，建立长期存活的双向流
    2. 客户端先发送一条 handshake 消息（携带 client_id / client_name）
    3. UE 服务端验证并注册会话，此后进入数据交换阶段
    4. 客户端持续向流写入 frame 消息（上行：Python -> UE）
    5. UE 向流写入 frame 消息（下行：UE -> Python）
    6. 任一方关闭流或发生错误时，连接终止

    多客户端特性：
    - 不同 Python 进程各自建立独立的 DataChannel 流
    - 每个流的 handshake 使用不同的 client_id
    - UE 端内部维护 per-client 发送队列，回包按 client_id 精确路由
    - 客户端之间互不干扰、不广播
    ============================================================
    """

    def DataChannel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomNetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DataChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.DataChannel,
                    request_deserializer=custom__network__pb2.StreamMessage.FromString,
                    response_serializer=custom__network__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uhmp.customnetwork.CustomNetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uhmp.customnetwork.CustomNetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomNetworkService(object):
    """============================================================
    CustomNetworkService
    ============================================================
    gRPC 服务定义：单 RPC，双向流模式。

    调用流程（从客户端视角）：
    1. 客户端调用 DataChannel，建立长期存活的双向流
    2. 客户端先发送一条 handshake 消息（携带 client_id / client_name）
    3. UE 服务端验证并注册会话，此后进入数据交换阶段
    4. 客户端持续向流写入 frame 消息（上行：Python -> UE）
    5. UE 向流写入 frame 消息（下行：UE -> Python）
    6. 任一方关闭流或发生错误时，连接终止

    多客户端特性：
    - 不同 Python 进程各自建立独立的 DataChannel 流
    - 每个流的 handshake 使用不同的 client_id
    - UE 端内部维护 per-client 发送队列，回包按 client_id 精确路由
    - 客户端之间互不干扰、不广播
    ============================================================
    """

    @staticmethod
    def DataChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/uhmp.customnetwork.CustomNetworkService/DataChannel',
            custom__network__pb2.StreamMessage.SerializeToString,
            custom__network__pb2.StreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
