# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ustom_network.proto\x12\x12uhmp.customnetwork\x1a\nutil.proto\"G\n\x0b\x43onnectInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x10\n\x08priority\x18\x04 \x01(\x05\"%\n\tHandshake\x12\x18\n\x10protocol_version\x18\x01 \x01(\x05\"%\n\x07Prepare\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"*\n\x07Payload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tsleepTime\x18\x02 \x01(\x02\"$\n\x06\x46inish\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xb4\x02\n\rStreamMessage\x12-\n\x04info\x18\x01 \x01(\x0b\x32\x1f.uhmp.customnetwork.ConnectInfo\x12,\n\x06\x63ustom\x18\x02 \x01(\x0b\x32\x1a.uhmp.customnetwork.CustomH\x00\x12\x32\n\thandshake\x18\x03 \x01(\x0b\x32\x1d.uhmp.customnetwork.HandshakeH\x00\x12.\n\x07prepare\x18\x04 \x01(\x0b\x32\x1b.uhmp.customnetwork.PrepareH\x00\x12,\n\x05\x66rame\x18\x05 \x01(\x0b\x32\x1b.uhmp.customnetwork.PayloadH\x00\x12,\n\x06\x66inish\x18\x06 \x01(\x0b\x32\x1a.uhmp.customnetwork.FinishH\x00\x42\x06\n\x04\x62ody2o\n\x14\x43ustomNetworkService\x12W\n\x0b\x44\x61taChannel\x12!.uhmp.customnetwork.StreamMessage\x1a!.uhmp.customnetwork.StreamMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTINFO']._serialized_start=56
  _globals['_CONNECTINFO']._serialized_end=127
  _globals['_HANDSHAKE']._serialized_start=129
  _globals['_HANDSHAKE']._serialized_end=166
  _globals['_PREPARE']._serialized_start=168
  _globals['_PREPARE']._serialized_end=205
  _globals['_PAYLOAD']._serialized_start=207
  _globals['_PAYLOAD']._serialized_end=249
  _globals['_FINISH']._serialized_start=251
  _globals['_FINISH']._serialized_end=287
  _globals['_STREAMMESSAGE']._serialized_start=290
  _globals['_STREAMMESSAGE']._serialized_end=598
  _globals['_CUSTOMNETWORKSERVICE']._serialized_start=600
  _globals['_CUSTOMNETWORKSERVICE']._serialized_end=711
# @@protoc_insertion_point(module_scope)
